/** Semantic groups keep gameplay independent from individual filenames. */
export const ASSET_GROUPS = Object.freeze({
  boot: Object.freeze({
    "background-placeholder": "assets/environment/strategy-galaxy-background-v1.png",
    "background-void": "assets/environment/void.png",
    "background-stars": "assets/environment/stars.png",
    "background-planet": "assets/environment/planet.png",
    "background-asteroid": "assets/environment/asteroid.png",
    "structure-hq": "assets/structures/command-hq-topdown-v1.png",
    "structure-turret": "assets/structures/defense-turret-topdown-v1.png",
    "structure-node": "assets/structures/energy-relay-topdown-v1.png",
    "nairan-scout": "assets/factions/nairan/scout.png",
    "nairan-fighter": "assets/factions/nairan/fighter.png",
    "nairan-bomber": "assets/factions/nairan/bomber.png",
    "nairan-frigate": "assets/factions/nairan/frigate.png",
    "klaed-scout": "assets/factions/klaed/scout.png",
    "klaed-fighter": "assets/factions/klaed/fighter.png",
    "klaed-bomber": "assets/factions/klaed/bomber.png",
    "klaed-frigate": "assets/factions/klaed/frigate.png",
    "nairan-bolt": "assets/projectiles/nairan-bolt.png",
    "klaed-bullet": "assets/projectiles/klaed-bullet.png",
  }),
  ships: Object.freeze({
    "nairan-scout-engine": "assets/factions/nairan/scout-engine.png",
    "nairan-scout-weapon": "assets/factions/nairan/scout-weapon.png",
    "nairan-scout-shield": "assets/factions/nairan/scout-shield.png",
    "nairan-scout-destruction": "assets/factions/nairan/scout-destruction.png",
    "nairan-fighter-engine": "assets/factions/nairan/fighter-engine.png",
    "nairan-fighter-weapon": "assets/factions/nairan/fighter-weapon.png",
    "nairan-fighter-shield": "assets/factions/nairan/fighter-shield.png",
    "nairan-fighter-destruction": "assets/factions/nairan/fighter-destruction.png",
    "nairan-bomber-engine": "assets/factions/nairan/bomber-engine.png",
    "nairan-bomber-shield": "assets/factions/nairan/bomber-shield.png",
    "nairan-bomber-destruction": "assets/factions/nairan/bomber-destruction.png",
    "nairan-frigate-engine": "assets/factions/nairan/frigate-engine.png",
    "nairan-frigate-weapon": "assets/factions/nairan/frigate-weapon.png",
    "nairan-frigate-shield": "assets/factions/nairan/frigate-shield.png",
    "nairan-frigate-destruction": "assets/factions/nairan/frigate-destruction.png",
    "klaed-scout-engine": "assets/factions/klaed/scout-engine.png",
    "klaed-scout-weapon": "assets/factions/klaed/scout-weapon.png",
    "klaed-scout-shield": "assets/factions/klaed/scout-shield.png",
    "klaed-scout-destruction": "assets/factions/klaed/scout-destruction.png",
    "klaed-fighter-engine": "assets/factions/klaed/fighter-engine.png",
    "klaed-fighter-weapon": "assets/factions/klaed/fighter-weapon.png",
    "klaed-fighter-shield": "assets/factions/klaed/fighter-shield.png",
    "klaed-fighter-destruction": "assets/factions/klaed/fighter-destruction.png",
    "klaed-bomber-engine": "assets/factions/klaed/bomber-engine.png",
    "klaed-bomber-shield": "assets/factions/klaed/bomber-shield.png",
    "klaed-bomber-destruction": "assets/factions/klaed/bomber-destruction.png",
    "klaed-frigate-engine": "assets/factions/klaed/frigate-engine.png",
    "klaed-frigate-weapon": "assets/factions/klaed/frigate-weapon.png",
    "klaed-frigate-shield": "assets/factions/klaed/frigate-shield.png",
    "klaed-frigate-destruction": "assets/factions/klaed/frigate-destruction.png",
  }),
  effects: Object.freeze({
    "nairan-ray": "assets/projectiles/nairan-ray.png",
    "nairan-rocket": "assets/projectiles/nairan-rocket.png",
    "nairan-torpedo": "assets/projectiles/nairan-torpedo.png",
    "klaed-big-bullet": "assets/projectiles/klaed-big-bullet.png",
    "klaed-ray": "assets/projectiles/klaed-ray.png",
    "klaed-torpedo": "assets/projectiles/klaed-torpedo.png",
    "klaed-wave": "assets/projectiles/klaed-wave.png",
  }),
  ui: Object.freeze({}),
});

export const mergeAssetGroups = (...groups) => Object.assign({}, ...groups);
