/** Semantic groups keep loading proportional to the selected level. */
export const ASSET_GROUPS = Object.freeze({
  boot: Object.freeze({
    "background-placeholder": "assets/runtime/environment/strategy-galaxy-background-v1.png",
    "unified-player-scout": "assets/factions/unified/player-scout-v2.png",
    "unified-player-drone": "assets/factions/unified/player-drone-v1.png",
    "unified-player-fighter": "assets/factions/unified/player-fighter-v2.png",
    "unified-player-bomber": "assets/factions/unified/player-bomber-v2.png",
    "unified-player-frigate": "assets/factions/unified/player-frigate-v2.png",
    "unified-enemy-scout": "assets/factions/unified/enemy-scout-v2.png",
    "unified-enemy-drone": "assets/factions/unified/enemy-drone-v1.png",
    "unified-enemy-fighter": "assets/factions/unified/enemy-fighter-v2.png",
    "unified-enemy-bomber": "assets/factions/unified/enemy-bomber-v2.png",
    "unified-enemy-frigate": "assets/factions/unified/enemy-frigate-v2.png",
    "unified-player-scout-pulse": "assets/projectiles/unified/player-scout-pulse-v2.png",
    "unified-player-fighter-laser": "assets/projectiles/unified/player-fighter-laser-v2.png",
    "unified-player-siege-missile": "assets/projectiles/unified/player-siege-missile-v2.png",
    "unified-player-heavy-cannon": "assets/projectiles/unified/player-heavy-cannon-v2.png",
    "unified-enemy-scout-pulse": "assets/projectiles/unified/enemy-scout-pulse-v2.png",
    "unified-enemy-fighter-laser": "assets/projectiles/unified/enemy-fighter-laser-v2.png",
    "unified-enemy-siege-missile": "assets/projectiles/unified/enemy-siege-missile-v2.png",
    "unified-enemy-heavy-cannon": "assets/projectiles/unified/enemy-heavy-cannon-v2.png",
    "ui-command-medallion": "assets/runtime/ui/orbital-command-medallion-v1.png",
  }),
  level1: Object.freeze({
    "background-orbital-garden-rival": "assets/runtime/environment/orbital-garden-rival-sector-v1.png",
    "background-orbital-garden-player": "assets/runtime/environment/orbital-garden-player-sector-v1.png",
  }),
  level2: Object.freeze({
    "background-twin-foundries-rival": "assets/runtime/environment/twin-foundries-rival-sector-v1.png",
    "background-twin-foundries-player": "assets/runtime/environment/twin-foundries-player-sector-v1.png",
  }),
  // Retained for later feature-enabled maps, but excluded from the core-map load
  // and Pages deployment while nodes and defensive structures are switched off.
  optionalStructures: Object.freeze({
    "structure-hq-garden": "assets/runtime/structures/orbital-garden-hq-v2.png",
    "structure-hq-garden-rival": "assets/runtime/structures/orbital-garden-hq-rival-v1.png",
    "structure-turret-head-garden": "assets/runtime/structures/orbital-garden-turret-head-v1.png",
    "structure-node-sunwell": "assets/runtime/structures/orbital-sunwell-v2.png",
    "structure-turret-garden-player": "assets/runtime/structures/orbital-garden-turret-player-v3.png",
    "structure-turret-garden-rival": "assets/runtime/structures/orbital-garden-turret-rival-v3.png",
    "structure-hq": "assets/structures/command-hq-topdown-v3.png",
    "structure-turret": "assets/structures/defense-turret-base-topdown-v2.png",
    "structure-turret-head": "assets/structures/defense-turret-head-topdown-v3.png",
    "structure-node-unified": "assets/structures/energy-relay-unified-v1.png",
  }),
  combatVfx: Object.freeze({
    "nairan-scout-engine": "assets/factions/nairan/scout-engine.png",
    "klaed-scout-engine": "assets/factions/klaed/scout-engine.png",
    "nairan-scout-destruction": "assets/factions/nairan/scout-destruction.png",
    "nairan-fighter-destruction": "assets/factions/nairan/fighter-destruction.png",
    "nairan-bomber-destruction": "assets/factions/nairan/bomber-destruction.png",
    "nairan-frigate-destruction": "assets/factions/nairan/frigate-destruction.png",
    "klaed-scout-destruction": "assets/factions/klaed/scout-destruction.png",
    "klaed-fighter-destruction": "assets/factions/klaed/fighter-destruction.png",
    "klaed-bomber-destruction": "assets/factions/klaed/bomber-destruction.png",
    "klaed-frigate-destruction": "assets/factions/klaed/frigate-destruction.png",
  }),
  // Retained source strips remain validated, but are deliberately excluded from boot.
  ships: Object.freeze({
    "nairan-scout-engine": "assets/factions/nairan/scout-engine.png",
    "nairan-scout-weapon": "assets/factions/nairan/scout-weapon.png",
    "nairan-scout-shield": "assets/factions/nairan/scout-shield.png",
    "nairan-scout-destruction": "assets/factions/nairan/scout-destruction.png",
    "nairan-fighter-engine": "assets/factions/nairan/fighter-engine.png",
    "nairan-fighter-weapon": "assets/factions/nairan/fighter-weapon.png",
    "nairan-fighter-shield": "assets/factions/nairan/fighter-shield.png",
    "nairan-fighter-destruction": "assets/factions/nairan/fighter-destruction.png",
    "nairan-bomber-engine": "assets/factions/nairan/bomber-engine.png",
    "nairan-bomber-shield": "assets/factions/nairan/bomber-shield.png",
    "nairan-bomber-destruction": "assets/factions/nairan/bomber-destruction.png",
    "nairan-frigate-engine": "assets/factions/nairan/frigate-engine.png",
    "nairan-frigate-weapon": "assets/factions/nairan/frigate-weapon.png",
    "nairan-frigate-shield": "assets/factions/nairan/frigate-shield.png",
    "nairan-frigate-destruction": "assets/factions/nairan/frigate-destruction.png",
    "klaed-scout-engine": "assets/factions/klaed/scout-engine.png",
    "klaed-scout-weapon": "assets/factions/klaed/scout-weapon.png",
    "klaed-scout-shield": "assets/factions/klaed/scout-shield.png",
    "klaed-scout-destruction": "assets/factions/klaed/scout-destruction.png",
    "klaed-fighter-engine": "assets/factions/klaed/fighter-engine.png",
    "klaed-fighter-weapon": "assets/factions/klaed/fighter-weapon.png",
    "klaed-fighter-shield": "assets/factions/klaed/fighter-shield.png",
    "klaed-fighter-destruction": "assets/factions/klaed/fighter-destruction.png",
    "klaed-bomber-engine": "assets/factions/klaed/bomber-engine.png",
    "klaed-bomber-shield": "assets/factions/klaed/bomber-shield.png",
    "klaed-bomber-destruction": "assets/factions/klaed/bomber-destruction.png",
    "klaed-frigate-engine": "assets/factions/klaed/frigate-engine.png",
    "klaed-frigate-weapon": "assets/factions/klaed/frigate-weapon.png",
    "klaed-frigate-shield": "assets/factions/klaed/frigate-shield.png",
    "klaed-frigate-destruction": "assets/factions/klaed/frigate-destruction.png",
  }),
  effects: Object.freeze({
    "nairan-bolt": "assets/projectiles/nairan-bolt.png",
    "nairan-ray": "assets/projectiles/nairan-ray.png",
    "nairan-rocket": "assets/projectiles/nairan-rocket.png",
    "nairan-torpedo": "assets/projectiles/nairan-torpedo.png",
    "klaed-bullet": "assets/projectiles/klaed-bullet.png",
    "klaed-big-bullet": "assets/projectiles/klaed-big-bullet.png",
    "klaed-ray": "assets/projectiles/klaed-ray.png",
    "klaed-torpedo": "assets/projectiles/klaed-torpedo.png",
    "klaed-wave": "assets/projectiles/klaed-wave.png",
  }),
  ui: Object.freeze({}),
});

export const mergeAssetGroups = (...groups) => Object.assign({}, ...groups);

export const runtimeAssetManifestForLevel = (level = 1) => mergeAssetGroups(
  ASSET_GROUPS.boot,
  Number(level) === 2 ? ASSET_GROUPS.level2 : ASSET_GROUPS.level1,
  ASSET_GROUPS.combatVfx,
);

export const levelAssetManifest = (level = 1) => Number(level) === 2 ? ASSET_GROUPS.level2 : ASSET_GROUPS.level1;
