export const CONFIG = Object.freeze({
  app: Object.freeze({
    title: "Strategy Galalaxy",
    designWidth: 420,
    designHeight: 760,
  }),
  viewport: Object.freeze({
    maxDevicePixelRatio: 2,
    coarsePointerPixelRatio: 1.5,
  }),
  camera: Object.freeze({
    battlefieldTopInset: 64,
    battlefieldBottomInset: 74,
    battlefieldCommandBottomInset: 234,
    dragThreshold: 7,
    inertiaDamping: 9,
    maximumInertiaSpeed: 720,
  }),
  timing: Object.freeze({
    fixedStepSeconds: 1 / 60,
    maxFrameDeltaSeconds: 0.1,
    maxCatchUpSteps: 6,
    deploymentIntervalSeconds: 22,
  }),
  caps: Object.freeze({
    unitsPerLaneTeam: 40,
    projectilesPerLaneTeam: 64,
    projectiles: 220,
    particles: 240,
  }),
  balance: Object.freeze({
    startingEnergy: 300,
    energyCap: 780,
    baseIncomePerSecond: 16,
    nodeIncomePerSecond: 7,
    baseWaveDronesPerLane: 3,
    baseWaveDroneEscalationEverySeconds: 150,
    baseWaveDroneEscalationMaximumBonus: 2,
    nodeCaptureRatePerSecond: 50,
    economyUpgradeBaseCost: 220,
    economyUpgradeCostGrowth: 1.75,
    economyUpgradeIncomeBonus: 0.22,
    economyUpgradeMaxLevel: 2,
    weaponUpgradeBaseCost: 220,
    weaponUpgradeCostGrowth: 1.7,
    weaponUpgradeDamageBonus: 0.12,
    weaponUpgradeMaxLevel: 3,
    turretUpgradeBaseCost: 180,
    turretUpgradeCostGrowth: 1.65,
    turretUpgradeDamageBonus: 0.2,
    turretUpgradeMaxLevel: 4,
    escalation: Object.freeze([
      Object.freeze({ fromBattleSeconds: 0, multiplier: 1 }),
      Object.freeze({ fromBattleSeconds: 120, multiplier: 1.15 }),
      Object.freeze({ fromBattleSeconds: 240, multiplier: 1.3 }),
      Object.freeze({ fromBattleSeconds: 360, multiplier: 1.5 }),
    ]),
  }),
  assets: Object.freeze({
    timeoutMs: 30000,
    retryCount: 1,
    retryDelayMs: 350,
  }),
});
